// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh0QRdsRtVgBr_JeVzx-NfBXNYxyDgklg',
    appId: '1:688114842013:web:af1083e39bf6c811d7d774',
    messagingSenderId: '688114842013',
    projectId: 'umamoeknockoff',
    authDomain: 'umamoeknockoff.firebaseapp.com',
    storageBucket: 'umamoeknockoff.firebasestorage.app',
    measurementId: 'G-6Y0W6X1R4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGk-7AFTSyZ37bC6kub0nggLYMjBd8pmI',
    appId: '1:688114842013:android:41420d597fb0f61ad7d774',
    messagingSenderId: '688114842013',
    projectId: 'umamoeknockoff',
    storageBucket: 'umamoeknockoff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfuthKkChhDJQrZEwSN83xBeYe05pY9co',
    appId: '1:688114842013:ios:0bd68dd17c0433cbd7d774',
    messagingSenderId: '688114842013',
    projectId: 'umamoeknockoff',
    storageBucket: 'umamoeknockoff.firebasestorage.app',
    iosBundleId: 'com.example.mobileGakgak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfuthKkChhDJQrZEwSN83xBeYe05pY9co',
    appId: '1:688114842013:ios:0bd68dd17c0433cbd7d774',
    messagingSenderId: '688114842013',
    projectId: 'umamoeknockoff',
    storageBucket: 'umamoeknockoff.firebasestorage.app',
    iosBundleId: 'com.example.mobileGakgak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh0QRdsRtVgBr_JeVzx-NfBXNYxyDgklg',
    appId: '1:688114842013:web:bb921991bd94de53d7d774',
    messagingSenderId: '688114842013',
    projectId: 'umamoeknockoff',
    authDomain: 'umamoeknockoff.firebaseapp.com',
    storageBucket: 'umamoeknockoff.firebasestorage.app',
    measurementId: 'G-ETWDSNY6EB',
  );
}
